### PR TITLE
Added notification on first update setting, notification volume slider

### PR DESCRIPTION
**Pull request by AGameAnx**
Added notification on first update setting - prevents dialog and sound from playing when launching the browser.
Added a volume slider for notification sounds.

Tested for chrome only, needs non-english messages.

### CODE REVIEW

**Comment by Ndragomirov** [comment]
hi, 
volume settings is cool, 
but not sure about notification on first update, it will works only if user was logged in before browser restart.

**Comment by AGameAnx** [comment]
Hm, I didn't change anything about that at all. It seems to be inconsistent about notifying the user when logging in even before my change.

I'll see if I can fix that, make it more consistent across the board: Never notify on first update if the checkbox is off, always notify if it's on.

Right now it seems not to notify if the number of streams prior to logging out is the same as when you log in again, otherwise to me it appears to work as intended.

I described it as only being intended for browser restart on the pull request here, but the text on the checkbox says 'first update' which properly describes that it wouldn't notify when first logging in too. That was actually the intended behavior, I'm not sure if you want it to not notify only on browser restart, to me it would be fine either way.

**Comment by AGameAnx** [comment]
Hey, not quite sure if I should have posted a comment after the commits for you to take a look at them. I am not planning on updating it further unless you have any more issues with/suggestions for it, it worked as intended for these 3 days.

**Comment by Ndragomirov** [comment]
Hi, I will merge it as soon as i implement user notifications preferences.

**Pull request merged**
